/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomDialogs;

import java.util.ArrayList;
import java.util.Collections;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JRadioButton;

/**
 *
 * @author Patryk
 */
public class Quiz extends javax.swing.JDialog
{
    ArrayList<JRadioButton> _buttons;
    int _correct;
    String _question;
    ArrayList<String> _answers;
    /**
     * Creates new form Quiz
     * @param parent
     * @param modal
     * @param Question
     * @param Correct
     * @param Incorrect
     */
    
    
    public Quiz(java.awt.Frame parent, boolean modal, String Question, String Correct, String[] Incorrect)
    {
        super(parent, modal);
        _question = Question;
        
        _answers = new ArrayList<>();
        _answers.add(Correct);
        for(String incorrect : Incorrect)
        {
            _answers.add(incorrect);
        }
        Collections.shuffle(_answers);
        _correct = _answers.indexOf(Correct);
        _buttons = new ArrayList<>();
        initComponentsDynamic();
    }
    
    
    public boolean showDialog() {
    setVisible(true);
    return _buttons.get(_correct).isSelected();
    }
    
    private void initComponentsDynamic()
    {
        java.awt.GridBagConstraints gridBagConstraints;
        buttonGroup = new javax.swing.ButtonGroup();
        jLabelQuestion = new javax.swing.JLabel();
        jButtonSumbit = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quiz");
        getContentPane().setLayout(new java.awt.GridBagLayout());
        
        jLabelQuestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelQuestion.setText(_question);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabelQuestion, gridBagConstraints);
        
        for(int i = 0; i< _answers.size(); i++)
        {
            _buttons.add(new JRadioButton());
            
            
            buttonGroup.add(_buttons.get(i));
            _buttons.get(i).setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            _buttons.get(i).setText(_answers.get(i));
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = i+1;
            gridBagConstraints.gridwidth = 3;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints.ipady = 15;
            getContentPane().add(_buttons.get(i), gridBagConstraints);
            
            
        }
        
        jButtonSumbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSumbit.setText("Submit");
        jButtonSumbit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSumbitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        getContentPane().add(jButtonSumbit, gridBagConstraints);

        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        jLabelQuestion = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButtonSumbit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quiz");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelQuestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelQuestion.setText("Question, Question, Question");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabelQuestion, gridBagConstraints);

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        getContentPane().add(jRadioButton1, gridBagConstraints);

        buttonGroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("jRadioButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        getContentPane().add(jRadioButton2, gridBagConstraints);

        buttonGroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("jRadioButton3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        getContentPane().add(jRadioButton3, gridBagConstraints);

        buttonGroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setText("jRadioButton4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        getContentPane().add(jRadioButton4, gridBagConstraints);

        jButtonSumbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSumbit.setText("Submit");
        jButtonSumbit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSumbitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        getContentPane().add(jButtonSumbit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSumbitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSumbitActionPerformed
    {//GEN-HEADEREND:event_jButtonSumbitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSumbitActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonSumbit;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
