/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomDialogs;

/**
 *
 * @author Patryk
 */
public class StringPrompt extends javax.swing.JDialog
{
    public class Response
    {
        public String Answer;
        public boolean OKPressed;

        public Response(String Answer, boolean OKPressed)
        {
            this.Answer = Answer;
            this.OKPressed = OKPressed;
        } 
        public Response()
        {
            this.OKPressed = false;
        } 
    }

    Response _response;
    /**
     * Creates new form StringPrompt
     */
    public StringPrompt(java.awt.Frame parent, boolean modal, String prompt)
    {
        super(parent, modal);
        initComponents();
        _response = new Response();
        jLabelPrompt.setText("    " + prompt + "    ");
        repaint();
        revalidate();
        pack();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelPrompt = new javax.swing.JLabel();
        jTextFieldAnswer = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelPrompt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPrompt.setText("Text");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        getContentPane().add(jLabelPrompt, gridBagConstraints);

        jTextFieldAnswer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldAnswer.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jTextFieldAnswerPropertyChange(evt);
            }
        });
        jTextFieldAnswer.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTextFieldAnswerKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jTextFieldAnswer, gridBagConstraints);

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButtonCancel, gridBagConstraints);

        jButtonOK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.setMaximumSize(new java.awt.Dimension(83, 31));
        jButtonOK.setMinimumSize(new java.awt.Dimension(83, 31));
        jButtonOK.setPreferredSize(new java.awt.Dimension(83, 31));
        jButtonOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButtonOK, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        _response.Answer = jTextFieldAnswer.getText().trim();
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOKActionPerformed
    {//GEN-HEADEREND:event_jButtonOKActionPerformed
        _response.Answer = jTextFieldAnswer.getText().trim();
        _response.OKPressed = true;
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jTextFieldAnswerPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jTextFieldAnswerPropertyChange
    {//GEN-HEADEREND:event_jTextFieldAnswerPropertyChange
        jButtonOK.setEnabled(jTextFieldAnswer.getText().trim().length() > 0);
    }//GEN-LAST:event_jTextFieldAnswerPropertyChange

    private void jTextFieldAnswerKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldAnswerKeyPressed
    {//GEN-HEADEREND:event_jTextFieldAnswerKeyPressed
        jButtonOK.setEnabled(jTextFieldAnswer.getText().trim().length() > 0);
    }//GEN-LAST:event_jTextFieldAnswerKeyPressed

    public Response showDialog() {
    setVisible(true);
    return _response;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelPrompt;
    private javax.swing.JTextField jTextFieldAnswer;
    // End of variables declaration//GEN-END:variables
}
