/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parent;

/**
 *
 * @author Patryk
 */
public class ChildTab extends javax.swing.JPanel
{

    /**
     * Creates new form ChildTab
     */
    public ChildTab()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        editBlacklist2 = new Parent.EditBlacklist();
        editWhitelist2 = new Parent.EditWhitelist();
        activityLog1 = new Parent.ActivityLog();

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane2.addTab("Edit Blacklist", editBlacklist2);
        jTabbedPane2.addTab("Edit Whitelist", editWhitelist2);
        jTabbedPane2.addTab("Activity Log", activityLog1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Parent.ActivityLog activityLog1;
    private Parent.EditBlacklist editBlacklist2;
    private Parent.EditWhitelist editWhitelist2;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
