/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parent;

import CustomDialogs.StringPrompt;
import java.awt.Container;
import java.awt.Frame;
import java.awt.Window;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author patry
 */
public class ManageChildren extends javax.swing.JPanel {

    DefaultListModel<String> _children;
    /**
     * Creates new form ManageUsers
     */
    public ManageChildren(List<String> children) {
        initComponents();
        jButtonRemoveChild.setEnabled(false);
        _children = new DefaultListModel<>();
        for(String child : children)
            _children.addElement(child);
        jListChildList.setModel(_children);
    }
    public ManageChildren() {
        initComponents();
        jButtonRemoveChild.setEnabled(false);
        _children = new DefaultListModel<>();
        jListChildList.setModel(_children);
    }
    
    public void UpdateChildren(List<String> children)
    {
        for(String child : children)
        {
            _children.addElement(child);
        }
        jListChildList.setModel(_children);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonRemoveChild = new javax.swing.JButton();
        jButtonAddChild = new javax.swing.JButton();
        jListChildList = new javax.swing.JList<>();

        jButtonRemoveChild.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRemoveChild.setText("Remove Child");
        jButtonRemoveChild.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRemoveChildActionPerformed(evt);
            }
        });

        jButtonAddChild.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAddChild.setText("Add Child");
        jButtonAddChild.setMaximumSize(new java.awt.Dimension(141, 31));
        jButtonAddChild.setMinimumSize(new java.awt.Dimension(141, 31));
        jButtonAddChild.setPreferredSize(new java.awt.Dimension(141, 31));
        jButtonAddChild.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddChildActionPerformed(evt);
            }
        });

        jListChildList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jListChildList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Steven", "Patryk" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListChildList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jListChildListMouseReleased(evt);
            }
        });
        jListChildList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jListChildListValueChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jListChildList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRemoveChild)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jButtonAddChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jListChildList, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoveChild)
                    .addComponent(jButtonAddChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListChildListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListChildListValueChanged
    {//GEN-HEADEREND:event_jListChildListValueChanged
        //System.out.println(jListChildList.getSelectedValuesList());
        
    }//GEN-LAST:event_jListChildListValueChanged

    int lastSelectedIndex;
    private void jListChildListMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jListChildListMouseReleased
    {//GEN-HEADEREND:event_jListChildListMouseReleased
        int index = jListChildList.locationToIndex(evt.getPoint());

        if (index != -1 && index == lastSelectedIndex) {
            jListChildList.clearSelection();
        }
        lastSelectedIndex = jListChildList.getSelectedIndex();
        System.out.println(jListChildList.getSelectedValuesList());
        jButtonRemoveChild.setEnabled(lastSelectedIndex != -1);
    }//GEN-LAST:event_jListChildListMouseReleased

    private void jButtonRemoveChildActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRemoveChildActionPerformed
    {//GEN-HEADEREND:event_jButtonRemoveChildActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove this child?", "Are you sure?", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION)
        {
            //removeChild
            _children.removeElementAt(jListChildList.getSelectedIndex());
        }
    }//GEN-LAST:event_jButtonRemoveChildActionPerformed

    private void jButtonAddChildActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddChildActionPerformed
    {//GEN-HEADEREND:event_jButtonAddChildActionPerformed
        Container parent = this; // this is a JPanel
        do {
            parent = parent.getParent();
        } while (!(parent instanceof Window) && parent != null);
        if (parent != null) { }
        CustomDialogs.StringPrompt prompt = new CustomDialogs.StringPrompt((Frame) parent, true, "Please Enter Child's Name");
        CustomDialogs.StringPrompt.Response response = prompt.showDialog();
        if(response.OKPressed)
        {
            System.out.println(response.Answer);
            //Add child
            _children.addElement(response.Answer);
            jListChildList.setModel(_children);
        }
    }//GEN-LAST:event_jButtonAddChildActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddChild;
    private javax.swing.JButton jButtonRemoveChild;
    private javax.swing.JList<String> jListChildList;
    // End of variables declaration//GEN-END:variables
}
