package Parent;


import Parent.ManageChildren;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patryk
 */
public class ParentView extends javax.swing.JPanel
{

    /**
     * Creates new form ParentView
     */
    public ParentView()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        manageChildren1 = new Parent.ManageChildren();
        notificationSettings2 = new Parent.NotificationSettings();
        childTab4 = new Parent.ChildTab();

        setPreferredSize(new java.awt.Dimension(226, 300));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(420, 326));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(420, 326));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(420, 326));
        jTabbedPane1.addTab("Manage Children", manageChildren1);
        jTabbedPane1.addTab("Notification Settings", notificationSettings2);
        jTabbedPane1.addTab("Patryk", childTab4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Parent.ChildTab childTab4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private Parent.ManageChildren manageChildren1;
    private Parent.NotificationSettings notificationSettings2;
    // End of variables declaration//GEN-END:variables
}
