package LogIn;

import java.awt.Event;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.event.EventListenerList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patryk
 */
public class LoginPrompt extends javax.swing.JPanel
{
    protected EventListenerList listenerList = new EventListenerList();
    /**
     * Creates new form LoginPrompt
     */
    public LoginPrompt()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelForgotPassword = new javax.swing.JLabel();
        jButtonLogIn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(434, 144));

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUserName.setText("User Name: ");

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPassword.setText("Password:");

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldUsername.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jTextFieldUsernamePropertyChange(evt);
            }
        });
        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTextFieldUsernameKeyPressed(evt);
            }
        });

        jPasswordFieldPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldPassword.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jPasswordFieldPasswordPropertyChange(evt);
            }
        });
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jPasswordFieldPasswordKeyPressed(evt);
            }
        });

        jLabelForgotPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelForgotPassword.setForeground(new java.awt.Color(0, 0, 204));
        jLabelForgotPassword.setText("I Forget Password");
        jLabelForgotPassword.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelForgotPasswordMouseClicked(evt);
            }
        });

        jButtonLogIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLogIn.setText("Log In");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName)
                            .addComponent(jLabelPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldPassword)
                            .addComponent(jTextFieldUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelForgotPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(jButtonLogIn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelForgotPassword)
                    .addComponent(jButtonLogIn))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelForgotPasswordMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelForgotPasswordMouseClicked
    {//GEN-HEADEREND:event_jLabelForgotPasswordMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new URI("http://www.piilossa.com/"));
        }
        catch (URISyntaxException ex) {
            Logger.getLogger(LoginPrompt.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex) {
            Logger.getLogger(LoginPrompt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelForgotPasswordMouseClicked

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLogInActionPerformed
    {//GEN-HEADEREND:event_jButtonLogInActionPerformed
        this.setVisible(false);
        ((LoginScreen)SwingUtilities.windowForComponent(this)).SetUserNamePassword(jTextFieldUsername.getText(), new String(jPasswordFieldPassword.getPassword()));
        this.firePropertyChange("Visibility", true, false);
    }//GEN-LAST:event_jButtonLogInActionPerformed

    private void jTextFieldUsernamePropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jTextFieldUsernamePropertyChange
    {//GEN-HEADEREND:event_jTextFieldUsernamePropertyChange
        jButtonLogIn.setEnabled(!(jTextFieldUsername.getText().isEmpty() || jPasswordFieldPassword.getPassword().length == 0));
    }//GEN-LAST:event_jTextFieldUsernamePropertyChange

    private void jPasswordFieldPasswordPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jPasswordFieldPasswordPropertyChange
    {//GEN-HEADEREND:event_jPasswordFieldPasswordPropertyChange
        jButtonLogIn.setEnabled(!(jTextFieldUsername.getText().isEmpty() || jPasswordFieldPassword.getPassword().length == 0));
    }//GEN-LAST:event_jPasswordFieldPasswordPropertyChange

    private void jTextFieldUsernameKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldUsernameKeyPressed
    {//GEN-HEADEREND:event_jTextFieldUsernameKeyPressed
        jButtonLogIn.setEnabled(!(jTextFieldUsername.getText().isEmpty() || jPasswordFieldPassword.getPassword().length == 0));
    }//GEN-LAST:event_jTextFieldUsernameKeyPressed

    private void jPasswordFieldPasswordKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPasswordFieldPasswordKeyPressed
    {//GEN-HEADEREND:event_jPasswordFieldPasswordKeyPressed
        jButtonLogIn.setEnabled(!(jTextFieldUsername.getText().isEmpty() || jPasswordFieldPassword.getPassword().length == 0));
    }//GEN-LAST:event_jPasswordFieldPasswordKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelForgotPassword;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
