/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogIn;

import javax.swing.SwingUtilities;

/**
 *
 * @author Patryk
 */
public class ModeSelectScreen extends javax.swing.JPanel
{

    /**
     * Creates new form ModeSelectScreen
     */
    public ModeSelectScreen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroupModeSelect = new javax.swing.ButtonGroup();
        jRadioButtonParent = new javax.swing.JRadioButton();
        jLabelPrompt = new javax.swing.JLabel();
        jRadioButtonChild = new javax.swing.JRadioButton();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();

        buttonGroupModeSelect.add(jRadioButtonParent);
        jRadioButtonParent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonParent.setText("Parent");
        jRadioButtonParent.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jRadioButtonParentStateChanged(evt);
            }
        });
        jRadioButtonParent.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jRadioButtonParentPropertyChange(evt);
            }
        });

        jLabelPrompt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPrompt.setText("Is this Installation for a Child User or a Parent User?");

        buttonGroupModeSelect.add(jRadioButtonChild);
        jRadioButtonChild.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonChild.setText("Child");
        jRadioButtonChild.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jRadioButtonChildStateChanged(evt);
            }
        });
        jRadioButtonChild.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jRadioButtonChildPropertyChange(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelName.setText("Name:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioButtonChild, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jLabelName, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioButtonChild, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jTextFieldName, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButtonOk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonChild)
                            .addComponent(jRadioButtonParent)
                            .addComponent(jLabelPrompt))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPrompt)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonParent)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonChild)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOkActionPerformed
    {//GEN-HEADEREND:event_jButtonOkActionPerformed

        ((LoginScreen)SwingUtilities.windowForComponent(this)).setUser(jRadioButtonChild.isSelected() ? LoginScreen.User.CHILD : LoginScreen.User.PARENT);
        ((LoginScreen)SwingUtilities.windowForComponent(this)).setChildName(jTextFieldName.getText());
        SwingUtilities.windowForComponent(this).dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jRadioButtonParentPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jRadioButtonParentPropertyChange
    {//GEN-HEADEREND:event_jRadioButtonParentPropertyChange
        jButtonOk.setEnabled(jRadioButtonChild.isSelected() || jRadioButtonParent.isSelected());
    }//GEN-LAST:event_jRadioButtonParentPropertyChange

    private void jRadioButtonChildPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jRadioButtonChildPropertyChange
    {//GEN-HEADEREND:event_jRadioButtonChildPropertyChange
        jButtonOk.setEnabled(jRadioButtonChild.isSelected() || jRadioButtonParent.isSelected());
    }//GEN-LAST:event_jRadioButtonChildPropertyChange

    private void jRadioButtonParentStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jRadioButtonParentStateChanged
    {//GEN-HEADEREND:event_jRadioButtonParentStateChanged
        jButtonOk.setEnabled(jRadioButtonChild.isSelected() || jRadioButtonParent.isSelected());
    }//GEN-LAST:event_jRadioButtonParentStateChanged

    private void jRadioButtonChildStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jRadioButtonChildStateChanged
    {//GEN-HEADEREND:event_jRadioButtonChildStateChanged
        jButtonOk.setEnabled(jRadioButtonChild.isSelected() || jRadioButtonParent.isSelected());
    }//GEN-LAST:event_jRadioButtonChildStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupModeSelect;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPrompt;
    private javax.swing.JRadioButton jRadioButtonChild;
    private javax.swing.JRadioButton jRadioButtonParent;
    private javax.swing.JTextField jTextFieldName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
